/**
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MoosendApi);
  }
}(this, function(expect, MoosendApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MoosendApi.ABCampaignData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ABCampaignData', function() {
    it('should create an instance of ABCampaignData', function() {
      // uncomment below and update the code to test ABCampaignData
      //var instane = new MoosendApi.ABCampaignData();
      //expect(instance).to.be.a(MoosendApi.ABCampaignData);
    });

    it('should have the property aBCampaignType (base name: "ABCampaignType")', function() {
      // uncomment below and update the code to test the property aBCampaignType
      //var instane = new MoosendApi.ABCampaignData();
      //expect(instance).to.be();
    });

    it('should have the property aBWinnerSelectionType (base name: "ABWinnerSelectionType")', function() {
      // uncomment below and update the code to test the property aBWinnerSelectionType
      //var instane = new MoosendApi.ABCampaignData();
      //expect(instance).to.be();
    });

    it('should have the property deliveredOnA (base name: "DeliveredOnA")', function() {
      // uncomment below and update the code to test the property deliveredOnA
      //var instane = new MoosendApi.ABCampaignData();
      //expect(instance).to.be();
    });

    it('should have the property deliveredOnB (base name: "DeliveredOnB")', function() {
      // uncomment below and update the code to test the property deliveredOnB
      //var instane = new MoosendApi.ABCampaignData();
      //expect(instance).to.be();
    });

    it('should have the property hTMLContentB (base name: "HTMLContentB")', function() {
      // uncomment below and update the code to test the property hTMLContentB
      //var instane = new MoosendApi.ABCampaignData();
      //expect(instance).to.be();
    });

    it('should have the property hoursToTest (base name: "HoursToTest")', function() {
      // uncomment below and update the code to test the property hoursToTest
      //var instane = new MoosendApi.ABCampaignData();
      //expect(instance).to.be();
    });

    it('should have the property ID (base name: "ID")', function() {
      // uncomment below and update the code to test the property ID
      //var instane = new MoosendApi.ABCampaignData();
      //expect(instance).to.be();
    });

    it('should have the property listPercentage (base name: "ListPercentage")', function() {
      // uncomment below and update the code to test the property listPercentage
      //var instane = new MoosendApi.ABCampaignData();
      //expect(instance).to.be();
    });

    it('should have the property plainContentB (base name: "PlainContentB")', function() {
      // uncomment below and update the code to test the property plainContentB
      //var instane = new MoosendApi.ABCampaignData();
      //expect(instance).to.be();
    });

    it('should have the property senderB (base name: "SenderB")', function() {
      // uncomment below and update the code to test the property senderB
      //var instane = new MoosendApi.ABCampaignData();
      //expect(instance).to.be();
    });

    it('should have the property subjectB (base name: "SubjectB")', function() {
      // uncomment below and update the code to test the property subjectB
      //var instane = new MoosendApi.ABCampaignData();
      //expect(instance).to.be();
    });

    it('should have the property webLocationB (base name: "WebLocationB")', function() {
      // uncomment below and update the code to test the property webLocationB
      //var instane = new MoosendApi.ABCampaignData();
      //expect(instance).to.be();
    });

  });

}));
