/**
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MoosendApi);
  }
}(this, function(expect, MoosendApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MoosendApi.AddingCriteriaToSegmentsRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AddingCriteriaToSegmentsRequest', function() {
    it('should create an instance of AddingCriteriaToSegmentsRequest', function() {
      // uncomment below and update the code to test AddingCriteriaToSegmentsRequest
      //var instane = new MoosendApi.AddingCriteriaToSegmentsRequest();
      //expect(instance).to.be.a(MoosendApi.AddingCriteriaToSegmentsRequest);
    });

    it('should have the property field (base name: "Field")', function() {
      // uncomment below and update the code to test the property field
      //var instane = new MoosendApi.AddingCriteriaToSegmentsRequest();
      //expect(instance).to.be();
    });

    it('should have the property value (base name: "Value")', function() {
      // uncomment below and update the code to test the property value
      //var instane = new MoosendApi.AddingCriteriaToSegmentsRequest();
      //expect(instance).to.be();
    });

    it('should have the property comparer (base name: "Comparer")', function() {
      // uncomment below and update the code to test the property comparer
      //var instane = new MoosendApi.AddingCriteriaToSegmentsRequest();
      //expect(instance).to.be();
    });

    it('should have the property dateFrom (base name: "DateFrom")', function() {
      // uncomment below and update the code to test the property dateFrom
      //var instane = new MoosendApi.AddingCriteriaToSegmentsRequest();
      //expect(instance).to.be();
    });

    it('should have the property dateTo (base name: "DateTo")', function() {
      // uncomment below and update the code to test the property dateTo
      //var instane = new MoosendApi.AddingCriteriaToSegmentsRequest();
      //expect(instance).to.be();
    });

  });

}));
