/**
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MoosendApi);
  }
}(this, function(expect, MoosendApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MoosendApi.Campaign();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Campaign', function() {
    it('should create an instance of Campaign', function() {
      // uncomment below and update the code to test Campaign
      //var instane = new MoosendApi.Campaign();
      //expect(instance).to.be.a(MoosendApi.Campaign);
    });

    it('should have the property aBCampaignType (base name: "ABCampaignType")', function() {
      // uncomment below and update the code to test the property aBCampaignType
      //var instane = new MoosendApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property aBHoursToTest (base name: "ABHoursToTest")', function() {
      // uncomment below and update the code to test the property aBHoursToTest
      //var instane = new MoosendApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property aBWinner (base name: "ABWinner")', function() {
      // uncomment below and update the code to test the property aBWinner
      //var instane = new MoosendApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property aBWinnerSelectionType (base name: "ABWinnerSelectionType")', function() {
      // uncomment below and update the code to test the property aBWinnerSelectionType
      //var instane = new MoosendApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property confirmationTo (base name: "ConfirmationTo")', function() {
      // uncomment below and update the code to test the property confirmationTo
      //var instane = new MoosendApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property createdOn (base name: "CreatedOn")', function() {
      // uncomment below and update the code to test the property createdOn
      //var instane = new MoosendApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property deliveredOn (base name: "DeliveredOn")', function() {
      // uncomment below and update the code to test the property deliveredOn
      //var instane = new MoosendApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property ID (base name: "ID")', function() {
      // uncomment below and update the code to test the property ID
      //var instane = new MoosendApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property isTransactional (base name: "IsTransactional")', function() {
      // uncomment below and update the code to test the property isTransactional
      //var instane = new MoosendApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property mailingLists (base name: "MailingLists")', function() {
      // uncomment below and update the code to test the property mailingLists
      //var instane = new MoosendApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "Name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new MoosendApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property recipientsCount (base name: "RecipientsCount")', function() {
      // uncomment below and update the code to test the property recipientsCount
      //var instane = new MoosendApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property scheduledFor (base name: "ScheduledFor")', function() {
      // uncomment below and update the code to test the property scheduledFor
      //var instane = new MoosendApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property scheduledForTimezone (base name: "ScheduledForTimezone")', function() {
      // uncomment below and update the code to test the property scheduledForTimezone
      //var instane = new MoosendApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property siteName (base name: "SiteName")', function() {
      // uncomment below and update the code to test the property siteName
      //var instane = new MoosendApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "Status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new MoosendApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property subject (base name: "Subject")', function() {
      // uncomment below and update the code to test the property subject
      //var instane = new MoosendApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property totalBounces (base name: "TotalBounces")', function() {
      // uncomment below and update the code to test the property totalBounces
      //var instane = new MoosendApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property totalComplaints (base name: "TotalComplaints")', function() {
      // uncomment below and update the code to test the property totalComplaints
      //var instane = new MoosendApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property totalForwards (base name: "TotalForwards")', function() {
      // uncomment below and update the code to test the property totalForwards
      //var instane = new MoosendApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property totalLinkClicks (base name: "TotalLinkClicks")', function() {
      // uncomment below and update the code to test the property totalLinkClicks
      //var instane = new MoosendApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property totalOpens (base name: "TotalOpens")', function() {
      // uncomment below and update the code to test the property totalOpens
      //var instane = new MoosendApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property totalSent (base name: "TotalSent")', function() {
      // uncomment below and update the code to test the property totalSent
      //var instane = new MoosendApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property totalUnsubscribes (base name: "TotalUnsubscribes")', function() {
      // uncomment below and update the code to test the property totalUnsubscribes
      //var instane = new MoosendApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property uniqueForwards (base name: "UniqueForwards")', function() {
      // uncomment below and update the code to test the property uniqueForwards
      //var instane = new MoosendApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property uniqueLinkClicks (base name: "UniqueLinkClicks")', function() {
      // uncomment below and update the code to test the property uniqueLinkClicks
      //var instane = new MoosendApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property uniqueOpens (base name: "UniqueOpens")', function() {
      // uncomment below and update the code to test the property uniqueOpens
      //var instane = new MoosendApi.Campaign();
      //expect(instance).to.be();
    });

  });

}));
