/**
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MoosendApi);
  }
}(this, function(expect, MoosendApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MoosendApi.Context84();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Context84', function() {
    it('should create an instance of Context84', function() {
      // uncomment below and update the code to test Context84
      //var instane = new MoosendApi.Context84();
      //expect(instance).to.be.a(MoosendApi.Context84);
    });

    it('should have the property aBCampaignData (base name: "ABCampaignData")', function() {
      // uncomment below and update the code to test the property aBCampaignData
      //var instane = new MoosendApi.Context84();
      //expect(instance).to.be();
    });

    it('should have the property confirmationTo (base name: "ConfirmationTo")', function() {
      // uncomment below and update the code to test the property confirmationTo
      //var instane = new MoosendApi.Context84();
      //expect(instance).to.be();
    });

    it('should have the property createdOn (base name: "CreatedOn")', function() {
      // uncomment below and update the code to test the property createdOn
      //var instane = new MoosendApi.Context84();
      //expect(instance).to.be();
    });

    it('should have the property deliveredOn (base name: "DeliveredOn")', function() {
      // uncomment below and update the code to test the property deliveredOn
      //var instane = new MoosendApi.Context84();
      //expect(instance).to.be();
    });

    it('should have the property formatType (base name: "FormatType")', function() {
      // uncomment below and update the code to test the property formatType
      //var instane = new MoosendApi.Context84();
      //expect(instance).to.be();
    });

    it('should have the property hTMLContent (base name: "HTMLContent")', function() {
      // uncomment below and update the code to test the property hTMLContent
      //var instane = new MoosendApi.Context84();
      //expect(instance).to.be();
    });

    it('should have the property ID (base name: "ID")', function() {
      // uncomment below and update the code to test the property ID
      //var instane = new MoosendApi.Context84();
      //expect(instance).to.be();
    });

    it('should have the property isTransactional (base name: "IsTransactional")', function() {
      // uncomment below and update the code to test the property isTransactional
      //var instane = new MoosendApi.Context84();
      //expect(instance).to.be();
    });

    it('should have the property mailingLists (base name: "MailingLists")', function() {
      // uncomment below and update the code to test the property mailingLists
      //var instane = new MoosendApi.Context84();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "Name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new MoosendApi.Context84();
      //expect(instance).to.be();
    });

    it('should have the property plainContent (base name: "PlainContent")', function() {
      // uncomment below and update the code to test the property plainContent
      //var instane = new MoosendApi.Context84();
      //expect(instance).to.be();
    });

    it('should have the property replyToEmail (base name: "ReplyToEmail")', function() {
      // uncomment below and update the code to test the property replyToEmail
      //var instane = new MoosendApi.Context84();
      //expect(instance).to.be();
    });

    it('should have the property scheduledFor (base name: "ScheduledFor")', function() {
      // uncomment below and update the code to test the property scheduledFor
      //var instane = new MoosendApi.Context84();
      //expect(instance).to.be();
    });

    it('should have the property sender (base name: "Sender")', function() {
      // uncomment below and update the code to test the property sender
      //var instane = new MoosendApi.Context84();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "Status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new MoosendApi.Context84();
      //expect(instance).to.be();
    });

    it('should have the property subject (base name: "Subject")', function() {
      // uncomment below and update the code to test the property subject
      //var instane = new MoosendApi.Context84();
      //expect(instance).to.be();
    });

    it('should have the property timezone (base name: "Timezone")', function() {
      // uncomment below and update the code to test the property timezone
      //var instane = new MoosendApi.Context84();
      //expect(instance).to.be();
    });

    it('should have the property updatedOn (base name: "UpdatedOn")', function() {
      // uncomment below and update the code to test the property updatedOn
      //var instane = new MoosendApi.Context84();
      //expect(instance).to.be();
    });

    it('should have the property webLocation (base name: "WebLocation")', function() {
      // uncomment below and update the code to test the property webLocation
      //var instane = new MoosendApi.Context84();
      //expect(instance).to.be();
    });

  });

}));
