/**
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MoosendApi);
  }
}(this, function(expect, MoosendApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MoosendApi.Context118();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Context118', function() {
    it('should create an instance of Context118', function() {
      // uncomment below and update the code to test Context118
      //var instane = new MoosendApi.Context118();
      //expect(instance).to.be.a(MoosendApi.Context118);
    });

    it('should have the property aBVersion (base name: "ABVersion")', function() {
      // uncomment below and update the code to test the property aBVersion
      //var instane = new MoosendApi.Context118();
      //expect(instance).to.be();
    });

    it('should have the property campaignDeliveredOn (base name: "CampaignDeliveredOn")', function() {
      // uncomment below and update the code to test the property campaignDeliveredOn
      //var instane = new MoosendApi.Context118();
      //expect(instance).to.be();
    });

    it('should have the property campaignID (base name: "CampaignID")', function() {
      // uncomment below and update the code to test the property campaignID
      //var instane = new MoosendApi.Context118();
      //expect(instance).to.be();
    });

    it('should have the property campaignIsArchived (base name: "CampaignIsArchived")', function() {
      // uncomment below and update the code to test the property campaignIsArchived
      //var instane = new MoosendApi.Context118();
      //expect(instance).to.be();
    });

    it('should have the property campaignName (base name: "CampaignName")', function() {
      // uncomment below and update the code to test the property campaignName
      //var instane = new MoosendApi.Context118();
      //expect(instance).to.be();
    });

    it('should have the property campaignSubject (base name: "CampaignSubject")', function() {
      // uncomment below and update the code to test the property campaignSubject
      //var instane = new MoosendApi.Context118();
      //expect(instance).to.be();
    });

    it('should have the property from (base name: "From")', function() {
      // uncomment below and update the code to test the property from
      //var instane = new MoosendApi.Context118();
      //expect(instance).to.be();
    });

    it('should have the property mailingLists (base name: "MailingLists")', function() {
      // uncomment below and update the code to test the property mailingLists
      //var instane = new MoosendApi.Context118();
      //expect(instance).to.be();
    });

    it('should have the property sent (base name: "Sent")', function() {
      // uncomment below and update the code to test the property sent
      //var instane = new MoosendApi.Context118();
      //expect(instance).to.be();
    });

    it('should have the property to (base name: "To")', function() {
      // uncomment below and update the code to test the property to
      //var instane = new MoosendApi.Context118();
      //expect(instance).to.be();
    });

    it('should have the property totalBounces (base name: "TotalBounces")', function() {
      // uncomment below and update the code to test the property totalBounces
      //var instane = new MoosendApi.Context118();
      //expect(instance).to.be();
    });

    it('should have the property totalComplaints (base name: "TotalComplaints")', function() {
      // uncomment below and update the code to test the property totalComplaints
      //var instane = new MoosendApi.Context118();
      //expect(instance).to.be();
    });

    it('should have the property totalForwards (base name: "TotalForwards")', function() {
      // uncomment below and update the code to test the property totalForwards
      //var instane = new MoosendApi.Context118();
      //expect(instance).to.be();
    });

    it('should have the property totalLinkClicks (base name: "TotalLinkClicks")', function() {
      // uncomment below and update the code to test the property totalLinkClicks
      //var instane = new MoosendApi.Context118();
      //expect(instance).to.be();
    });

    it('should have the property totalOpens (base name: "TotalOpens")', function() {
      // uncomment below and update the code to test the property totalOpens
      //var instane = new MoosendApi.Context118();
      //expect(instance).to.be();
    });

    it('should have the property totalUnsubscribes (base name: "TotalUnsubscribes")', function() {
      // uncomment below and update the code to test the property totalUnsubscribes
      //var instane = new MoosendApi.Context118();
      //expect(instance).to.be();
    });

    it('should have the property uniqueForwards (base name: "UniqueForwards")', function() {
      // uncomment below and update the code to test the property uniqueForwards
      //var instane = new MoosendApi.Context118();
      //expect(instance).to.be();
    });

    it('should have the property uniqueLinkClicks (base name: "UniqueLinkClicks")', function() {
      // uncomment below and update the code to test the property uniqueLinkClicks
      //var instane = new MoosendApi.Context118();
      //expect(instance).to.be();
    });

    it('should have the property uniqueOpens (base name: "UniqueOpens")', function() {
      // uncomment below and update the code to test the property uniqueOpens
      //var instane = new MoosendApi.Context118();
      //expect(instance).to.be();
    });

  });

}));
