/**
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MoosendApi);
  }
}(this, function(expect, MoosendApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MoosendApi.ImportOperation19();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ImportOperation19', function() {
    it('should create an instance of ImportOperation19', function() {
      // uncomment below and update the code to test ImportOperation19
      //var instane = new MoosendApi.ImportOperation19();
      //expect(instance).to.be.a(MoosendApi.ImportOperation19);
    });

    it('should have the property completedOn (base name: "CompletedOn")', function() {
      // uncomment below and update the code to test the property completedOn
      //var instane = new MoosendApi.ImportOperation19();
      //expect(instance).to.be();
    });

    it('should have the property createdOn (base name: "CreatedOn")', function() {
      // uncomment below and update the code to test the property createdOn
      //var instane = new MoosendApi.ImportOperation19();
      //expect(instance).to.be();
    });

    it('should have the property dataHash (base name: "DataHash")', function() {
      // uncomment below and update the code to test the property dataHash
      //var instane = new MoosendApi.ImportOperation19();
      //expect(instance).to.be();
    });

    it('should have the property emailNotify (base name: "EmailNotify")', function() {
      // uncomment below and update the code to test the property emailNotify
      //var instane = new MoosendApi.ImportOperation19();
      //expect(instance).to.be();
    });

    it('should have the property ID (base name: "ID")', function() {
      // uncomment below and update the code to test the property ID
      //var instane = new MoosendApi.ImportOperation19();
      //expect(instance).to.be();
    });

    it('should have the property mappings (base name: "Mappings")', function() {
      // uncomment below and update the code to test the property mappings
      //var instane = new MoosendApi.ImportOperation19();
      //expect(instance).to.be();
    });

    it('should have the property message (base name: "Message")', function() {
      // uncomment below and update the code to test the property message
      //var instane = new MoosendApi.ImportOperation19();
      //expect(instance).to.be();
    });

    it('should have the property skipNewMembers (base name: "SkipNewMembers")', function() {
      // uncomment below and update the code to test the property skipNewMembers
      //var instane = new MoosendApi.ImportOperation19();
      //expect(instance).to.be();
    });

    it('should have the property startedOn (base name: "StartedOn")', function() {
      // uncomment below and update the code to test the property startedOn
      //var instane = new MoosendApi.ImportOperation19();
      //expect(instance).to.be();
    });

    it('should have the property success (base name: "Success")', function() {
      // uncomment below and update the code to test the property success
      //var instane = new MoosendApi.ImportOperation19();
      //expect(instance).to.be();
    });

    it('should have the property totalDuplicate (base name: "TotalDuplicate")', function() {
      // uncomment below and update the code to test the property totalDuplicate
      //var instane = new MoosendApi.ImportOperation19();
      //expect(instance).to.be();
    });

    it('should have the property totalIgnored (base name: "TotalIgnored")', function() {
      // uncomment below and update the code to test the property totalIgnored
      //var instane = new MoosendApi.ImportOperation19();
      //expect(instance).to.be();
    });

    it('should have the property totalInserted (base name: "TotalInserted")', function() {
      // uncomment below and update the code to test the property totalInserted
      //var instane = new MoosendApi.ImportOperation19();
      //expect(instance).to.be();
    });

    it('should have the property totalInvalid (base name: "TotalInvalid")', function() {
      // uncomment below and update the code to test the property totalInvalid
      //var instane = new MoosendApi.ImportOperation19();
      //expect(instance).to.be();
    });

    it('should have the property totalMembers (base name: "TotalMembers")', function() {
      // uncomment below and update the code to test the property totalMembers
      //var instane = new MoosendApi.ImportOperation19();
      //expect(instance).to.be();
    });

    it('should have the property totalUnsubscribed (base name: "TotalUnsubscribed")', function() {
      // uncomment below and update the code to test the property totalUnsubscribed
      //var instane = new MoosendApi.ImportOperation19();
      //expect(instance).to.be();
    });

    it('should have the property totalUpdated (base name: "TotalUpdated")', function() {
      // uncomment below and update the code to test the property totalUpdated
      //var instane = new MoosendApi.ImportOperation19();
      //expect(instance).to.be();
    });

  });

}));
