/**
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MoosendApi);
  }
}(this, function(expect, MoosendApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MoosendApi.MailingList();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MailingList', function() {
    it('should create an instance of MailingList', function() {
      // uncomment below and update the code to test MailingList
      //var instane = new MoosendApi.MailingList();
      //expect(instance).to.be.a(MoosendApi.MailingList);
    });

    it('should have the property activeMemberCount (base name: "ActiveMemberCount")', function() {
      // uncomment below and update the code to test the property activeMemberCount
      //var instane = new MoosendApi.MailingList();
      //expect(instance).to.be();
    });

    it('should have the property bouncedMemberCount (base name: "BouncedMemberCount")', function() {
      // uncomment below and update the code to test the property bouncedMemberCount
      //var instane = new MoosendApi.MailingList();
      //expect(instance).to.be();
    });

    it('should have the property createdBy (base name: "CreatedBy")', function() {
      // uncomment below and update the code to test the property createdBy
      //var instane = new MoosendApi.MailingList();
      //expect(instance).to.be();
    });

    it('should have the property createdOn (base name: "CreatedOn")', function() {
      // uncomment below and update the code to test the property createdOn
      //var instane = new MoosendApi.MailingList();
      //expect(instance).to.be();
    });

    it('should have the property customFieldsDefinition (base name: "CustomFieldsDefinition")', function() {
      // uncomment below and update the code to test the property customFieldsDefinition
      //var instane = new MoosendApi.MailingList();
      //expect(instance).to.be();
    });

    it('should have the property ID (base name: "ID")', function() {
      // uncomment below and update the code to test the property ID
      //var instane = new MoosendApi.MailingList();
      //expect(instance).to.be();
    });

    it('should have the property importOperation (base name: "ImportOperation")', function() {
      // uncomment below and update the code to test the property importOperation
      //var instane = new MoosendApi.MailingList();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "Name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new MoosendApi.MailingList();
      //expect(instance).to.be();
    });

    it('should have the property removedMemberCount (base name: "RemovedMemberCount")', function() {
      // uncomment below and update the code to test the property removedMemberCount
      //var instane = new MoosendApi.MailingList();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "Status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new MoosendApi.MailingList();
      //expect(instance).to.be();
    });

    it('should have the property unsubscribedMemberCount (base name: "UnsubscribedMemberCount")', function() {
      // uncomment below and update the code to test the property unsubscribedMemberCount
      //var instane = new MoosendApi.MailingList();
      //expect(instance).to.be();
    });

    it('should have the property updatedBy (base name: "UpdatedBy")', function() {
      // uncomment below and update the code to test the property updatedBy
      //var instane = new MoosendApi.MailingList();
      //expect(instance).to.be();
    });

    it('should have the property updatedOn (base name: "UpdatedOn")', function() {
      // uncomment below and update the code to test the property updatedOn
      //var instane = new MoosendApi.MailingList();
      //expect(instance).to.be();
    });

  });

}));
