/**
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MoosendApi);
  }
}(this, function(expect, MoosendApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MoosendApi.Paging76();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Paging76', function() {
    it('should create an instance of Paging76', function() {
      // uncomment below and update the code to test Paging76
      //var instane = new MoosendApi.Paging76();
      //expect(instance).to.be.a(MoosendApi.Paging76);
    });

    it('should have the property currentPage (base name: "CurrentPage")', function() {
      // uncomment below and update the code to test the property currentPage
      //var instane = new MoosendApi.Paging76();
      //expect(instance).to.be();
    });

    it('should have the property pageSize (base name: "PageSize")', function() {
      // uncomment below and update the code to test the property pageSize
      //var instane = new MoosendApi.Paging76();
      //expect(instance).to.be();
    });

    it('should have the property sortIsAscending (base name: "SortIsAscending")', function() {
      // uncomment below and update the code to test the property sortIsAscending
      //var instane = new MoosendApi.Paging76();
      //expect(instance).to.be();
    });

    it('should have the property totalPageCount (base name: "TotalPageCount")', function() {
      // uncomment below and update the code to test the property totalPageCount
      //var instane = new MoosendApi.Paging76();
      //expect(instance).to.be();
    });

    it('should have the property totalResults (base name: "TotalResults")', function() {
      // uncomment below and update the code to test the property totalResults
      //var instane = new MoosendApi.Paging76();
      //expect(instance).to.be();
    });

  });

}));
