/**
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MoosendApi);
  }
}(this, function(expect, MoosendApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MoosendApi.SegmentsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SegmentsApi', function() {
    describe('addingCriteriaToSegments', function() {
      it('should call addingCriteriaToSegments successfully', function(done) {
        //uncomment below and update the code to test addingCriteriaToSegments
        //instance.addingCriteriaToSegments(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('creatingANewSegment', function() {
      it('should call creatingANewSegment successfully', function(done) {
        //uncomment below and update the code to test creatingANewSegment
        //instance.creatingANewSegment(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deletingASegment', function() {
      it('should call deletingASegment successfully', function(done) {
        //uncomment below and update the code to test deletingASegment
        //instance.deletingASegment(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('gettingSegmentDetails', function() {
      it('should call gettingSegmentDetails successfully', function(done) {
        //uncomment below and update the code to test gettingSegmentDetails
        //instance.gettingSegmentDetails(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('gettingSegmentSubscribers', function() {
      it('should call gettingSegmentSubscribers successfully', function(done) {
        //uncomment below and update the code to test gettingSegmentSubscribers
        //instance.gettingSegmentSubscribers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('gettingSegments', function() {
      it('should call gettingSegments successfully', function(done) {
        //uncomment below and update the code to test gettingSegments
        //instance.gettingSegments(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updatingASegment', function() {
      it('should call updatingASegment successfully', function(done) {
        //uncomment below and update the code to test updatingASegment
        //instance.updatingASegment(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updatingSegmentCriteria', function() {
      it('should call updatingSegmentCriteria successfully', function(done) {
        //uncomment below and update the code to test updatingSegmentCriteria
        //instance.updatingSegmentCriteria(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
