/**
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MoosendApi);
  }
}(this, function(expect, MoosendApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MoosendApi.SubscribersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SubscribersApi', function() {
    describe('addingMultipleSubscribers', function() {
      it('should call addingMultipleSubscribers successfully', function(done) {
        //uncomment below and update the code to test addingMultipleSubscribers
        //instance.addingMultipleSubscribers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addingSubscribers', function() {
      it('should call addingSubscribers successfully', function(done) {
        //uncomment below and update the code to test addingSubscribers
        //instance.addingSubscribers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSubscriberByEmailAddress', function() {
      it('should call getSubscriberByEmailAddress successfully', function(done) {
        //uncomment below and update the code to test getSubscriberByEmailAddress
        //instance.getSubscriberByEmailAddress(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSubscriberById', function() {
      it('should call getSubscriberById successfully', function(done) {
        //uncomment below and update the code to test getSubscriberById
        //instance.getSubscriberById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('gettingSubscribers', function() {
      it('should call gettingSubscribers successfully', function(done) {
        //uncomment below and update the code to test gettingSubscribers
        //instance.gettingSubscribers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removingASubscriber', function() {
      it('should call removingASubscriber successfully', function(done) {
        //uncomment below and update the code to test removingASubscriber
        //instance.removingASubscriber(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removingMultipleSubscribers', function() {
      it('should call removingMultipleSubscribers successfully', function(done) {
        //uncomment below and update the code to test removingMultipleSubscribers
        //instance.removingMultipleSubscribers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('unsubscribingSubscribersFromAccount', function() {
      it('should call unsubscribingSubscribersFromAccount successfully', function(done) {
        //uncomment below and update the code to test unsubscribingSubscribersFromAccount
        //instance.unsubscribingSubscribersFromAccount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('unsubscribingSubscribersFromMailingList', function() {
      it('should call unsubscribingSubscribersFromMailingList successfully', function(done) {
        //uncomment below and update the code to test unsubscribingSubscribersFromMailingList
        //instance.unsubscribingSubscribersFromMailingList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('unsubscribingSubscribersFromMailingListAndASpecifiedCampaign', function() {
      it('should call unsubscribingSubscribersFromMailingListAndASpecifiedCampaign successfully', function(done) {
        //uncomment below and update the code to test unsubscribingSubscribersFromMailingListAndASpecifiedCampaign
        //instance.unsubscribingSubscribersFromMailingListAndASpecifiedCampaign(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updatingASubscriber', function() {
      it('should call updatingASubscriber successfully', function(done) {
        //uncomment below and update the code to test updatingASubscriber
        //instance.updatingASubscriber(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
